on:
  push:
    branches:
      - main
name: zola-deploy-action
jobs:
  build:
    name: bjoernmichaelsen/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: bjoernmichaelsen/zola-deploy-action
      uses: bjoernmichaelsen/zola-deploy-action@master
      env:
        TOKEN: ${{ secrets.TOKEN }}
