name: Deploy Zola site to Pages
on:
  push:
    branches:
      - main


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to sh
defaults:
  run:
    shell: sh

jobs:
  build:
    name: Build Zola pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Build with Zola
      uses: bjoernmichaelsen/zola-deploy-action@main
#      env:
#        TOKEN: ${{ secrets.TOKEN }}
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
